stages:
  data_ingestion:
    cmd: python -m src.data.data_ingestion
    deps:
    - src/data/data_ingestion.py
    params:
    - data_ingestion.test_size
    outs:
    - data/raw
  data_preprocessing:
    cmd: python -m src.data.data_preprocessing
    deps:
    - data/raw
    - src/data/data_ingestion.py
    outs:
    - data/interim
  transform_feature:
    cmd: python -m src.features.transform_feature
    deps:
    - data/interim
    - src/features/transform_feature.py
    outs:
    - data/processed
    - models/target_encoder.pkl


  train_model:
    cmd: python -m src.model.train_model
    deps:
    - data/processed
    - src/model/train_model.py
    outs:
    - models/gradient_boosting_model.pkl
    - reports/data.json
  model_testing:
    cmd: python -m src.model.test_model
    deps:
    - data/processed
    - models/
    - reports/
    - src/model/test_model.py
